# Generated by Django 3.2.13 on 2024-07-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('DBS', 'DBS'), ('DGS', 'DGS'), ('DES', 'DES'), ('DPS (PRIVATE)', 'DPS (PRIVATE)'), ('DSS (SOE)', 'DSS (SOE)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JenisOBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JenisPengadaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('KOPEGTEL KEDIRI', 'KOPEGTEL KEDIRI'), ('KOPEGTEL MALANG', 'KOPEGTEL MALANG'), ('KOPKAR SMART MEDIA', 'KOPKAR SMART MEDIA'), ('PT ADMINISTRASI MEDIKA/ADMEDIKA', 'PT ADMINISTRASI MEDIKA/ADMEDIKA'), ('PT DIGITAL APLIKASI SOLUSI/DIGISERV', 'PT DIGITAL APLIKASI SOLUSI/DIGISERV'), ('PT DWIMITRA EKATAMA MANDIRI', 'PT DWIMITRA EKATAMA MANDIRI'), ('PT EL-KOKAR TIMUR', 'PT EL-KOKAR TIMUR'), ('PT GRAHA INFORMATIKA NUSANTARA/GRATIKA', 'PT GRAHA INFORMATIKA NUSANTARA/GRATIKA'), ('PT GREATSOFT SOLUSI INDONESIA', 'PT GREATSOFT SOLUSI INDONESIA'), ('PT INFOMEDIA NUSANTARA', 'PT INFOMEDIA NUSANTARA'), ('LAINNYA', 'LAINNYA')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Witel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('Surabaya Selatan', 'Surabaya Selatan'), ('Surabaya Utara', 'Surabaya Utara'), ('Denpasar', 'Denpasar'), ('Sidoarjo', 'Sidoarjo'), ('Malang', 'Malang'), ('Madura', 'Madura'), ('Pasuruan', 'Pasuruan'), ('Jember', 'Jember'), ('Kediri', 'Kediri'), ('Madiun', 'Madiun'), ('Singaraja', 'Singaraja'), ('NTT', 'NTT'), ('NTB', 'NTB')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JustifikasiOBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_project', models.PositiveSmallIntegerField(choices=[(2023, '2023'), (2024, '2024')])),
                ('idlop', models.CharField(max_length=50)),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('judul_kb', models.CharField(max_length=255)),
                ('nomor_kb', models.CharField(max_length=100)),
                ('estimasi_tanggal_kb', models.DateField()),
                ('jangka_waktu_kontrak', models.PositiveSmallIntegerField()),
                ('start_date_kontrak', models.DateField()),
                ('end_date_kontrak', models.DateField()),
                ('perkiraan_nilai_kontrak', models.DecimalField(decimal_places=2, max_digits=15)),
                ('skema_bayar', models.CharField(choices=[('On Time Charge (OTC)', 'On Time Charge (OTC)'), ('Monthly Recurring Charge (MRC)', 'Monthly Recurring Charge (MRC)'), ('Termin', 'Termin'), ('DP dan Pelunasan', 'DP dan Pelunasan')], max_length=50)),
                ('target_delivery', models.DateField()),
                ('pic_witel', models.CharField(max_length=255)),
                ('judul_justifikasi_obl', models.CharField(max_length=255)),
                ('perkiraan_nilai_obl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('target_billcomp', models.DateField()),
                ('nomor_pengadaan', models.CharField(max_length=100)),
                ('alasan_keterlambatan_pengajuan_obl', models.TextField()),
                ('bud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obldata.bud')),
                ('jenis_obl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obldata.jenisobl')),
                ('jenis_pengadaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obldata.jenispengadaan')),
                ('mitra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obldata.mitra')),
                ('witel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obldata.witel')),
            ],
        ),
    ]
