# Generated by Django 3.2.13 on 2024-09-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JustifikasiOBL2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witel', models.CharField(max_length=100)),
                ('bud', models.CharField(max_length=100)),
                ('tahunProject', models.CharField(max_length=4)),
                ('idlop', models.CharField(max_length=50)),
                ('namaPelanggan', models.CharField(max_length=255)),
                ('judulKontrakKB', models.CharField(max_length=255)),
                ('nomorKontrakKB', models.CharField(max_length=100)),
                ('estimasiTanggalKB', models.DateField()),
                ('jangkaWaktuKontrak', models.CharField(max_length=100)),
                ('startDateKontrak', models.DateField()),
                ('endDateKontrak', models.DateField()),
                ('perkiraanNilaiKontrak', models.DecimalField(decimal_places=2, max_digits=65)),
                ('skemaBayarPelanggan', models.CharField(max_length=100)),
                ('targetDelivery', models.DateField()),
                ('picWitel', models.CharField(max_length=100)),
                ('jenisOBL', models.CharField(max_length=50)),
                ('mitra', models.CharField(max_length=100)),
                ('judulJustifikasiOBL', models.CharField(max_length=255)),
                ('perkiraanNilaiPekerjaan', models.DecimalField(decimal_places=2, max_digits=65)),
                ('jenisPengadaan', models.CharField(max_length=100)),
                ('targetBillcomp', models.DateField()),
                ('nomorQuote', models.CharField(max_length=100)),
                ('alasanKeterlambatanOBL', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JustifikasiOBL2024',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witel', models.CharField(max_length=100)),
                ('bud', models.CharField(max_length=100)),
                ('tahunProject', models.CharField(max_length=4)),
                ('idlop', models.CharField(max_length=50)),
                ('namaPelanggan', models.CharField(max_length=255)),
                ('judulKontrakKB', models.CharField(max_length=255)),
                ('nomorKontrakKB', models.CharField(max_length=100)),
                ('estimasiTanggalKB', models.DateField()),
                ('jangkaWaktuKontrak', models.CharField(max_length=100)),
                ('startDateKontrak', models.DateField()),
                ('endDateKontrak', models.DateField()),
                ('perkiraanNilaiKontrak', models.DecimalField(decimal_places=2, max_digits=65)),
                ('skemaBayarPelanggan', models.CharField(max_length=100)),
                ('targetDelivery', models.DateField()),
                ('picWitel', models.CharField(max_length=100)),
                ('jenisOBL', models.CharField(max_length=50)),
                ('mitra', models.CharField(max_length=100)),
                ('judulJustifikasiOBL', models.CharField(max_length=255)),
                ('perkiraanNilaiPekerjaan', models.DecimalField(decimal_places=2, max_digits=65)),
                ('jenisPengadaan', models.CharField(max_length=100)),
                ('targetBillcomp', models.DateField()),
                ('nomorQuote', models.CharField(max_length=100)),
                ('alasanKeterlambatanOBL', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
